service: rds-stop

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  role: rdsStopRole


functions:
  stop:
    handler: handler.stop
    environment:
        INSTANCEID: 'aaa-server, bbb-server'
    events:
      - schedule: cron(0 12 ? * MON-FRI *)

resources:
  Resources:
    rdsStopRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: RDSStopRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: rdsStopPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - rds:StopDBInstance
                  Resource: "*"
